add_newline = false

format= "$directory$git_branch$git_commit$git_state$git_status$docker_context$scala$gleam$lua$nodejs$line_break$time$character"

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[time]
disabled = false

[scala]
symbol = ""

[java]
disabled = true

[python]
disabled = true
