add_newline = false

format=["directory", "git_branch", "git_commit", "git_status", "time", "line_break", "character" ]

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[time]
disabled = false

[scala]
format = "via [${symbol}]($style)"
symbol = " "

[java]
disabled = true
