add_newline = false

format= "$directory$git_branch$git_commit$git_status$scala$line_break$time$character"

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[time]
disabled = false

[scala]
format = "via [${symbol}]($style)"
detect_files = ['.scalaenv', '.sbtenv', 'build.sbt', 'build.sc', '.mill-version']
symbol = ""

[java]
disabled = true

[python]
disabled = true
