# enable this line and last line in order enable profiling of zsh load time
# zmodload zsh/zprof
autoload -U select-word-style
select-word-style bash

source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/setop.zsh
# source ~/.config/zsh/completion.zsh
source ~/.config/zsh/bindkeys.zsh
source ~/.config/zsh/exports.zsh
source ~/.config/zsh/functions.zsh
source ~/.config/zsh/secrets.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.config/bin/fzf-marks/fzf-marks.plugin.zsh

# setup completions in homebrew
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -U compinit
  compinit
fi

if which fzf > /dev/null; then
  source <(fzf --zsh)
fi

HISTDB_TABULATE_CMD=(sed -e $'s/\x1f/\t/g')
autoload -Uz add-zsh-hook

if which fnm > /dev/null; then
  eval "$(fnm env)"
fi
if which starship > /dev/null; then
  eval "$(starship init zsh)"
fi

export PATH="/usr/local/opt/openjdk@11/bin:$PATH"

if which zoxide > /dev/null; then
  eval "$(zoxide init --cmd cd zsh)"
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# zprof
