-- ordered list of plugins to test out when time permits
-- https://github.com/rhysd/git-messenger.vim
-- https://github.com/artemave/workspace-diagnostics.nvim
-- https://github.com/L3MON4D3/LuaSnip
-- https://github.com/fnune/recall.nvim
-- https://github.com/folke/sidekick.nvim
-- https://github.com/rachartier/tiny-code-action.nvim
-- https://github.com/kevinhwang91/nvim-ufo
-- https://github.com/gbprod/yanky.nvim
-- https://github.com/gennaro-tedesco/nvim-peekup
-- https://github.com/otavioschwanck/arrow.nvim

-- can probably just be added as something to my own config
-- https://github.com/fasterius/simple-zoom.nvim
